-- Q1. What is the total revenue generated by male vs. female customers?
SELECT
    gender,
    SUM(purchase_amount) AS revenue
FROM
    customer
GROUP BY
    gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT
    customer_id,
    purchase_amount
FROM
    customer
WHERE
    discount_applied = 'yes'
    and purchase_amount >= (
        select
            avg(purchase_amount)
        from
            customer
    );

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT
    item_purchased,
    round(avg(review_rating), 2) as avg_rating
FROM
    customer
group by
    item_purchased
order by
    avg_rating desc
limit
    5;

-- 4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select
    shipping_type,
    avg(purchase_amount)
from
    customer
where
    shipping_type in ('Standard', 'Express')
group by
    shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT
    subscription_status,
    COUNT(customer_id) AS no_of_customer,
    AVG(purchase_amount) AS average_spend,
    SUM(purchase_amount) AS total_revenue
FROM
    customer
GROUP BY
    subscription_status
ORDER BY
    total_revenue,
    average_spend DESC;

-- Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    item_purchased,
    ROUND(
        SUM(
            CASE
                WHEN discount_applied = 'yes' THEN 1
                ELSE 0
            END
        ) * 100 / COUNT(*),
        2
    ) AS percentage_of_purchase
FROM
    customer
GROUP BY
    item_purchased
ORDER BY
    percentage_of_purchase desc
LIMIT
    5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
with customer_type as(
    select
        previous_purchases,
        customer_id,
        case
            when previous_purchases = 1 then 'New'
            when previous_purchases between 2
            and 10 then 'Returning'
            else 'Loyal'
        end as customer_segment
    from
        customer
)
select
    customer_segment,
    count(*) as number_of_customers,
    round(
        count(*) * 100.0 / (
            select
                count(*)
            from
                customer_type
        ),
        2
    ) as percentage_of_customers
from
    customer_type
group by
    customer_segmnt;

-- Q8. What are the top 3 most purchased products within each category?
 
with item_count as(
    select
        category,
        item_purchased,
        count(customer_id) as total_orders
    from
        customer
    group by
        category,
        item_purchased
),
ranked_items as (
    select
        category,
        item_purchased,
        total_orders,
        row_number() over(
            partition by category
            order by
                total_orders desc
        ) as item_rank
    from
        item_count
)
select
    category,
    item_purchased,
    total_orders,
    item_rank
from
    ranked_items
where
    item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select
    subscription_status,
    count(customer_id) as repeated_buyers
from
    customer
where
    previous_purchases > 5
group by
    subscription_status;

-- Q10. What is the revenue contribution of each age group?
select
    age_group,
    sum(purchase_amount) as total_revenue
from
    customer
group by
    age_group
order by
    total_revenue desc;
